# Generated by Django 6.0.4 on 2026-04-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0002_aula_etapa_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=250)),
                ('etapa', models.CharField(choices=[('INF', 'Infantil'), ('PRI', 'Primaria'), ('ESO', 'ESO'), ('BAC', 'Bachillerato'), ('CIC', 'Ciclos'), ('OTR', 'Otros')], default='ESO', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.aula')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.materia')),
            ],
        ),
        migrations.CreateModel(
            name='TramoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia_semana', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1)),
            ],
            options={
                'verbose_name': 'Tramo Horario',
                'verbose_name_plural': 'Tramos Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.AddField(
            model_name='profesor',
            name='abreviatura',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.profesor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='tramo_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.tramohorario'),
        ),
    ]
