# Generated by Django 6.0.4 on 2026-04-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0003_grupo_horario_tramohorario_delete_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='abreviatura',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
