# Generated by Django 6.0.4 on 2026-04-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0004_alter_profesor_abreviatura_alter_profesor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='abrev',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='abrev',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
