# Generated by Django 6.0.4 on 2026-04-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0005_aula_abrev_alter_aula_nombre_alter_materia_abrev'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_guardia', models.CharField()),
                ('prioridad', models.IntegerField(default=0)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.profesor')),
                ('tramo_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.tramohorario')),
            ],
        ),
    ]
