# Generated by Django 6.0.4 on 2026-04-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0006_horarioguardia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioguardia',
            name='tipo_guardia',
            field=models.CharField(max_length=50),
        ),
    ]
