# Generated by Django 6.0.4 on 2026-04-09 12:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0007_alter_horarioguardia_tipo_guardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si la baja sigue activa', null=True, verbose_name='Fecha de fin')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='safa_guardias.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Actividad / Excursión')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(21, 30))),
                ('grupos_implicados', models.ManyToManyField(related_name='excursiones_asignadas', to='safa_guardias.grupo')),
                ('profesores_acompanantes', models.ManyToManyField(related_name='excursiones_asignadas', to='safa_guardias.profesor')),
            ],
        ),
    ]
