# Generated by Django 6.0.4 on 2026-04-09 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0008_bajaprofesor_salidaexcursion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellidos', 'nombre']},
        ),
        migrations.CreateModel(
            name='AusenciaPuntual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la ausencia')),
                ('hora_inicio', models.TimeField(verbose_name='Desde las...')),
                ('hora_fin', models.TimeField(verbose_name='Hasta las...')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias_puntuales', to='safa_guardias.profesor')),
            ],
            options={
                'verbose_name': 'Ausencia Puntual',
                'verbose_name_plural': 'Ausencias Puntuales',
            },
        ),
    ]
