# Generated by Django 6.0.4 on 2026-04-10 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0009_alter_profesor_options_ausenciapuntual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Centro (ej. 23000000)')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Centro Escolar',
                'verbose_name_plural': 'Centros Escolares',
            },
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={},
        ),
        migrations.AddField(
            model_name='profesor',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('DIRECCION', 'Dirección'), ('JEFATURA', 'Jefatura de Estudios'), ('PROFESOR', 'Profesorado')], default='PROFESOR', max_length=20, verbose_name='Rol en la plataforma'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='abreviatura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='safa_guardias.centroescolar'),
        ),
    ]
