# Generated by Django 6.0.4 on 2026-04-10 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0010_centroescolar_alter_profesor_options_profesor_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroescolar',
            name='comunidad_autonoma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centroescolar',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
