# Generated by Django 6.0.4 on 2026-04-10 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0011_centroescolar_comunidad_autonoma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='materia',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='salidaexcursion',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excursiones', to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='tramohorario',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='safa_guardias.centroescolar'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='abrev',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='abrev',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('centro', 'abrev')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('centro', 'abrev')},
        ),
    ]
