# Generated by Django 6.0.4 on 2026-04-10 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0012_aula_centro_grupo_centro_materia_centro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENT', 'Pendiente'), ('COB', 'Cubierta'), ('AUTO', 'Autogestionada (Sin profesor)')], default='PENT', max_length=4)),
                ('observaciones', models.TextField(blank=True)),
                ('motivo_ausencia', models.CharField(blank=True, max_length=200, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.aula')),
                ('ausencia_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_generadas', to='safa_guardias.ausenciapuntual')),
                ('baja_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_generadas', to='safa_guardias.bajaprofesor')),
                ('excursion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_generadas', to='safa_guardias.salidaexcursion')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.materia')),
                ('profesor_ausente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_perdidas', to='safa_guardias.profesor')),
                ('profesor_guardia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_atendidas', to='safa_guardias.profesor')),
                ('tramo_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.tramohorario')),
            ],
            options={
                'verbose_name': 'Registro de Guardia',
                'verbose_name_plural': 'Seguimiento de Guardias Diarias',
                'unique_together': {('fecha', 'tramo_horario', 'grupo', 'profesor_ausente')},
            },
        ),
    ]
