# Generated by Django 6.0.4 on 2026-04-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0013_registroguardia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausenciapuntual',
            options={},
        ),
        migrations.AddField(
            model_name='ausenciapuntual',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='bajaprofesor',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='horario',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='horarioguardia',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AddField(
            model_name='registroguardia',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AlterField(
            model_name='bajaprofesor',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('DIRECCION', 'Dirección'), ('JEFATURA', 'Jefatura de Estudios'), ('PROFESOR', 'Profesorado')], default='PROFESOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salidaexcursion',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AlterField(
            model_name='tramohorario',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('centro', 'nombre', 'curso', 'etapa')},
        ),
        migrations.AlterUniqueTogether(
            name='tramohorario',
            unique_together={('centro', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
