# Generated by Django 6.0.4 on 2026-04-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0014_alter_ausenciapuntual_options_ausenciapuntual_centro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Educación Secundaria Obligatoria', max_length=100)),
                ('siglas', models.CharField(help_text='Ej: ESO', max_length=10)),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safa_guardias.centroescolar')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'unique_together': {('centro', 'siglas')},
            },
        ),
    ]
