# Generated by Django 6.0.4 on 2026-04-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0015_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='etapa',
        ),
    ]
