# Generated by Django 6.0.4 on 2026-04-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0016_alter_grupo_options_alter_grupo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='safa_guardias.etapa'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('centro', 'nombre', 'curso', 'etapa')},
        ),
    ]
