# Generated by Django 6.0.4 on 2026-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa_guardias', '0017_grupo_etapa_alter_grupo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramohorario',
            name='es_recreo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tramohorario',
            name='etapas',
            field=models.ManyToManyField(blank=True, related_name='tramos', to='safa_guardias.etapa'),
        ),
    ]
